name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jashvanth370
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
